In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
#Summary dataset
df_summary = pd.read_csv('3-month-V2X/jan-22/summary_jan-22.csv')
#Host dataset
df_host = pd.read_csv('3-month-V2X/jan-22/host_jan-22.csv')

In [3]:
print(df_summary.shape)
print(df_host.shape)

(5710, 43)
(13627175, 44)

In [4]:
df_summary.head()

,uuid,segmentid,partitionDate,device,timestamp,filedate,filetimeutc,updateTimeMs,sequenceNo,vin,tripId,utctime,startlocaltime,endlocaltime,swversionmaj,swversionmin,startlatitude,startlongitude,endlatitude,endlongitude,startodometer,numBSMTx,numGNSSOutages,numCANOutages,firmwareVersionString,configsVersionString,fullMediaVersionString,deltaMediaVersionString,pluginsVersionString,totalStorageOnDevice,storageUsed,configVersion,endodometer,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,numIntersectionEncounters,timestamp_hr,updateTimeMs_hr,startlocaltime_hr,endlocaltime_hr
0,1640997773108110038,611a0e1208875eb72086a75d8ca78de2,2022-01-01,10038,1640997773108,20220101,4253,1668774694763851,1,0f6b1f657ac30ab76519ed4c677e9909,10038202201014253,1640997773108,2573108,3873488,NaN,NaN,NaN,NaN,27.800831,-82.307824,NaN,12266,1,1,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,51,0,0.0,0,0,0,0,0,0,2022-01-01 00:41:55.968,2022-11-18 12:31:34.763851074,2022-01-01 05:42:53.108,2022-01-01 06:04:33.488
1,1641003656021110429,119f15cecf793f3c7ae87edf4c2782bf,2022-01-01,10429,1641003656021,20220101,22056,1668774718762895,1,82077c274c8b1917a195adc43f641529,104292022010122056,1641003656021,8456021,9412107,NaN,NaN,NaN,NaN,27.904013,-82.358562,NaN,9053,0,0,TOYOTA-THEA-C-V1.5,00,TOYOTA-THEA-C-V1.5,00,00,12385,36,0,0.0,192,0,0,0,0,0,2022-01-01 02:20:14.208,2022-11-18 12:31:58.762895020,2022-01-01 07:20:56.021,2022-01-01 07:36:52.107
2,1641004870993110020,1d44a0ac41f3029d2e5d720a969d33f5,2022-01-01,10020,1641004870993,20220101,24111,1668774686353782,1,c1722a7941d61aad6e651a35b65a9c3e,100202022010124111,1641004870993,9670993,11945088,NaN,NaN,NaN,NaN,27.785137,-82.312088,NaN,22570,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.1,HONDA-THEA-C-V1.5,00,00,12385,51,0,0.0,0,0,166,0,0,3,2022-01-01 02:42:04.928,2022-11-18 12:31:26.353781982,2022-01-01 07:41:10.993,2022-01-01 08:19:05.088
3,1641005617238110032,8e4d37d0d317eee9a83d3ee7d57603cb,2022-01-01,10032,1641005617238,20220101,25337,1668774863683486,1,c63a5650dcd0bf04b35bd712466010bc,100322022010125337,1641005617238,10417238,10949738,NaN,NaN,27.814499,-82.312781,27.822904,-82.335471,0.0,5238,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,50,0,0.0,0,0,0,0,0,0,2022-01-01 02:53:00.288,2022-11-18 12:34:23.683486084,2022-01-01 07:53:37.238,2022-01-01 08:02:29.738
4,1641006036089110009,ce80a5f34c3393b581a330d931b3c600,2022-01-01,10009,1641006036089,20220101,30036,1668774835449449,1,483d8df877b31405c1e8fe4247f02d86,100092022010130036,1641006036089,10836089,10971353,NaN,NaN,NaN,NaN,27.712051,-82.334613,NaN,1221,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,50,0,0.0,0,0,0,0,0,0,2022-01-01 02:59:33.504,2022-11-18 12:33:55.449448975,2022-01-01 08:00:36.089,2022-01-01 08:02:51.353

In [5]:
df_summary['vin'].nunique()

129

In [6]:
df_host.head()

,uuid,segmentid,partitionDate,device,timestamp,filedate,filetimeutc,updateTimeMs,sequenceNo,vin,tripId,localTimeMs,latitude,longitude,elevation,heading,gpsspeed,fixtypehvgps,gpssemimajaxis,gpssemiminaxis,gpsorientsemimaj,speed,yawrate,longaccel,transstate,gpsUncertaintyArea,speedMph,gpsspeedMph,elevationFt,gpssemimajaxisFt,gpssemiminaxisFt,brakestatus,throttlepospct,steerangle,turnsignal,headlamp,wiper,stabilitycontrolstatus,absstatus,traccontrolstatus,closestintersectid,gpsUncertainFlag,timestamp_hr,updateTimeMs_hr
0,1640995200040181110014,6f813aebcbec975f467a1097ea94b802,2022-01-01,10014,1640995200040,20220101,234454,1678858665000,1811,7b9d31aa17b849b238ab79cef0733041,1001420220101234454,86400040,27.975867,-82.277571,-6.099000,270.24347,0.726,2.0,0.91,0.47,152.0,0.726,-0.000018,0.419822,2.0,1.343659,1.624016,1.624016,-20.009843,2.985564,1.541995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,False,2022-01-01 00:00:25.600,1970-01-20 10:20:58.665
1,1640995200055378610071,8ee8b375371d2fd0a4605848e4636989,2022-01-01,10071,1640995200055,20220101,232855,1678858665000,3786,4910fcdaedc2be5c5f05533b7a9cb8c2,1007120220101232855,86400055,27.917010,-82.285677,-14.942000,359.93253,18.858,2.0,0.57,0.48,4.3,18.858,0.241233,-0.073326,2.0,0.859540,42.184145,42.184145,-49.022310,1.870079,1.574803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,False,2022-01-01 00:00:25.600,1970-01-20 10:20:58.665
2,1640995200540181210014,6f813aebcbec975f467a1097ea94b802,2022-01-01,10014,1640995200540,20220101,234454,1678858665000,1812,7b9d31aa17b849b238ab79cef0733041,1001420220101234454,86400540,27.975867,-82.277575,-6.135000,270.24347,1.042,2.0,0.90,0.47,151.0,1.042,-0.000003,0.515054,2.0,1.328894,2.330888,2.330888,-20.127952,2.952756,1.541995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,False,2022-01-01 00:00:25.600,1970-01-20 10:20:58.665
3,1640995200555378710071,8ee8b375371d2fd0a4605848e4636989,2022-01-01,10071,1640995200555,20220101,232855,1678858665000,3787,4910fcdaedc2be5c5f05533b7a9cb8c2,1007120220101232855,86400555,27.917095,-82.285677,-14.835999,359.83844,18.845,2.0,0.57,0.48,4.5,18.845,0.021451,-0.058381,2.0,0.859540,42.155064,42.155064,-48.674539,1.870079,1.574803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,False,2022-01-01 00:00:25.600,1970-01-20 10:20:58.665
4,1640995201040181310014,6f813aebcbec975f467a1097ea94b802,2022-01-01,10014,1640995201040,20220101,234454,1678858665000,1813,7b9d31aa17b849b238ab79cef0733041,1001420220101234454,86401040,27.975865,-82.277582,-6.194000,262.26047,1.869,2.0,0.89,0.47,151.0,1.869,-10.275696,1.414231,2.0,1.314128,4.180834,4.180834,-20.321522,2.919948,1.541995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,False,2022-01-01 00:00:25.600,1970-01-20 10:20:58.665

In [7]:
df_summary.head()

,uuid,segmentid,partitionDate,device,timestamp,filedate,filetimeutc,updateTimeMs,sequenceNo,vin,tripId,utctime,startlocaltime,endlocaltime,swversionmaj,swversionmin,startlatitude,startlongitude,endlatitude,endlongitude,startodometer,numBSMTx,numGNSSOutages,numCANOutages,firmwareVersionString,configsVersionString,fullMediaVersionString,deltaMediaVersionString,pluginsVersionString,totalStorageOnDevice,storageUsed,configVersion,endodometer,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,numIntersectionEncounters,timestamp_hr,updateTimeMs_hr,startlocaltime_hr,endlocaltime_hr
0,1640997773108110038,611a0e1208875eb72086a75d8ca78de2,2022-01-01,10038,1640997773108,20220101,4253,1668774694763851,1,0f6b1f657ac30ab76519ed4c677e9909,10038202201014253,1640997773108,2573108,3873488,NaN,NaN,NaN,NaN,27.800831,-82.307824,NaN,12266,1,1,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,51,0,0.0,0,0,0,0,0,0,2022-01-01 00:41:55.968,2022-11-18 12:31:34.763851074,2022-01-01 05:42:53.108,2022-01-01 06:04:33.488
1,1641003656021110429,119f15cecf793f3c7ae87edf4c2782bf,2022-01-01,10429,1641003656021,20220101,22056,1668774718762895,1,82077c274c8b1917a195adc43f641529,104292022010122056,1641003656021,8456021,9412107,NaN,NaN,NaN,NaN,27.904013,-82.358562,NaN,9053,0,0,TOYOTA-THEA-C-V1.5,00,TOYOTA-THEA-C-V1.5,00,00,12385,36,0,0.0,192,0,0,0,0,0,2022-01-01 02:20:14.208,2022-11-18 12:31:58.762895020,2022-01-01 07:20:56.021,2022-01-01 07:36:52.107
2,1641004870993110020,1d44a0ac41f3029d2e5d720a969d33f5,2022-01-01,10020,1641004870993,20220101,24111,1668774686353782,1,c1722a7941d61aad6e651a35b65a9c3e,100202022010124111,1641004870993,9670993,11945088,NaN,NaN,NaN,NaN,27.785137,-82.312088,NaN,22570,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.1,HONDA-THEA-C-V1.5,00,00,12385,51,0,0.0,0,0,166,0,0,3,2022-01-01 02:42:04.928,2022-11-18 12:31:26.353781982,2022-01-01 07:41:10.993,2022-01-01 08:19:05.088
3,1641005617238110032,8e4d37d0d317eee9a83d3ee7d57603cb,2022-01-01,10032,1641005617238,20220101,25337,1668774863683486,1,c63a5650dcd0bf04b35bd712466010bc,100322022010125337,1641005617238,10417238,10949738,NaN,NaN,27.814499,-82.312781,27.822904,-82.335471,0.0,5238,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,50,0,0.0,0,0,0,0,0,0,2022-01-01 02:53:00.288,2022-11-18 12:34:23.683486084,2022-01-01 07:53:37.238,2022-01-01 08:02:29.738
4,1641006036089110009,ce80a5f34c3393b581a330d931b3c600,2022-01-01,10009,1641006036089,20220101,30036,1668774835449449,1,483d8df877b31405c1e8fe4247f02d86,100092022010130036,1641006036089,10836089,10971353,NaN,NaN,NaN,NaN,27.712051,-82.334613,NaN,1221,0,0,HONDA-THEA-C-V1.5,HONDA-THEA-C-V1.5.2,HONDA-THEA-C-V1.5,00,00,12385,50,0,0.0,0,0,0,0,0,0,2022-01-01 02:59:33.504,2022-11-18 12:33:55.449448975,2022-01-01 08:00:36.089,2022-01-01 08:02:51.353

In [8]:
df_summary.columns

Index(['uuid', 'segmentid', 'partitionDate', 'device', 'timestamp', 'filedate',
       'filetimeutc', 'updateTimeMs', 'sequenceNo', 'vin', 'tripId', 'utctime',
       'startlocaltime', 'endlocaltime', 'swversionmaj', 'swversionmin',
       'startlatitude', 'startlongitude', 'endlatitude', 'endlongitude',
       'startodometer', 'numBSMTx', 'numGNSSOutages', 'numCANOutages',
       'firmwareVersionString', 'configsVersionString',
       'fullMediaVersionString', 'deltaMediaVersionString',
       'pluginsVersionString', 'totalStorageOnDevice', 'storageUsed',
       'configVersion', 'endodometer', 'numNormalBSMRx', 'numShadowBSMRx',
       'numSPATRx', 'numWarnings', 'numInforms', 'numIntersectionEncounters',
       'timestamp_hr', 'updateTimeMs_hr', 'startlocaltime_hr',
       'endlocaltime_hr'],
      dtype='object')

In [9]:
df_host.columns

Index(['uuid', 'segmentid', 'partitionDate', 'device', 'timestamp', 'filedate',
       'filetimeutc', 'updateTimeMs', 'sequenceNo', 'vin', 'tripId',
       'localTimeMs', 'latitude', 'longitude', 'elevation', 'heading',
       'gpsspeed', 'fixtypehvgps', 'gpssemimajaxis', 'gpssemiminaxis',
       'gpsorientsemimaj', 'speed', 'yawrate', 'longaccel', 'transstate',
       'gpsUncertaintyArea', 'speedMph', 'gpsspeedMph', 'elevationFt',
       'gpssemimajaxisFt', 'gpssemiminaxisFt', 'brakestatus', 'throttlepospct',
       'steerangle', 'turnsignal', 'headlamp', 'wiper',
       'stabilitycontrolstatus', 'absstatus', 'traccontrolstatus',
       'closestintersectid', 'gpsUncertainFlag', 'timestamp_hr',
       'updateTimeMs_hr'],
      dtype='object')

In [10]:
df = pd.merge(df_summary[['tripId','device','startlocaltime',
                         'endlocaltime','startlatitude','startlongitude',
                         'endlatitude','endlongitude','numBSMTx', 'numGNSSOutages', 'numCANOutages',
                         'numNormalBSMRx', 'numShadowBSMRx',
                         'numSPATRx', 'numWarnings', 'numInforms', ]], 
              df_host[['tripId','speed','speedMph','filedate','filetimeutc',
                      'localTimeMs','latitude','longitude','gpsspeed','elevation',
                      'brakestatus','turnsignal','yawrate','longaccel']], on = 'tripId')

In [11]:
df.shape

(12698766, 29)

In [12]:
df.head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel
0,10038202201014253,10038,2573108,3873488,NaN,NaN,27.800831,-82.307824,12266,1,1,0,0,0,0,0,NaN,2236.93629,20220101,4253,2573608,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN
1,10038202201014253,10038,2573108,3873488,NaN,NaN,27.800831,-82.307824,12266,1,1,0,0,0,0,0,NaN,2236.93629,20220101,4253,2574108,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN
2,10038202201014253,10038,2573108,3873488,NaN,NaN,27.800831,-82.307824,12266,1,1,0,0,0,0,0,NaN,2236.93629,20220101,4253,2574608,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN
3,10038202201014253,10038,2573108,3873488,NaN,NaN,27.800831,-82.307824,12266,1,1,0,0,0,0,0,NaN,2236.93629,20220101,4253,2575108,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN
4,10038202201014253,10038,2573108,3873488,NaN,NaN,27.800831,-82.307824,12266,1,1,0,0,0,0,0,NaN,2236.93629,20220101,4253,2575608,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,NaN

In [13]:
df = df.sort_values(by = ['tripId','filedate','localTimeMs'])
df.head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel
6990566,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,2236.93629,20220120,733,453922,40.092302,-83.050165,0.012333,221.0,NaN,NaN,NaN,NaN
6990567,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,2236.93629,20220120,733,454422,40.092302,-83.050165,0.009764,221.0,NaN,NaN,NaN,NaN
6990568,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,2236.93629,20220120,733,454930,40.092302,-83.050165,0.011306,221.0,NaN,NaN,NaN,NaN
6990569,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,2236.93629,20220120,733,455536,40.092302,-83.050165,0.020042,221.0,NaN,NaN,NaN,NaN
6990570,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,2236.93629,20220120,733,456122,40.092302,-83.050165,0.013361,221.0,NaN,NaN,NaN,NaN

In [14]:
df['speedMph'] = df['speedMph'].apply(lambda x: x if x < 100 else np.nan)

In [15]:
df.head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel
6990566,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,453922,40.092302,-83.050165,0.012333,221.0,NaN,NaN,NaN,NaN
6990567,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,454422,40.092302,-83.050165,0.009764,221.0,NaN,NaN,NaN,NaN
6990568,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,454930,40.092302,-83.050165,0.011306,221.0,NaN,NaN,NaN,NaN
6990569,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,455536,40.092302,-83.050165,0.020042,221.0,NaN,NaN,NaN,NaN
6990570,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,456122,40.092302,-83.050165,0.013361,221.0,NaN,NaN,NaN,NaN

In [16]:
df['speedMph'].isna().mean()*100

2.229035482660284

In [17]:
df['speedMph'].describe()

count    1.241571e+07
mean     3.006742e+01
std      2.756718e+01
min      0.000000e+00
25%      0.000000e+00
50%      2.645798e+01
75%      5.227720e+01
max      9.999105e+01
Name: speedMph, dtype: float64

In [18]:
df['yawrate'] = df['yawrate'].apply(lambda x: x if abs(x) < 327.67 else np.nan)

In [19]:
df['yawrate_speed'] = abs(df['yawrate'])*df['speedMph']

In [20]:
df['yawrate_speed'].describe()

count    1.241445e+07
mean     3.140024e+01
std      7.649429e+01
min      0.000000e+00
25%      0.000000e+00
50%      5.940613e+00
75%      2.610346e+01
max      1.663901e+04
Name: yawrate_speed, dtype: float64

In [21]:
df.sort_values(by = 'yawrate_speed', ascending = False).head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel,yawrate_speed
678240,10049202201043011,10049,1811197,2056476,NaN,NaN,27.853822,-82.207737,1365,0,0,0,0,0,0,0,23.015,51.483089,20220104,3011,1918276,NaN,NaN,23.015,-11.918,0.0,0.0,-323.19370,0.248584,16639.009929
7882487,1041120220121190138,10411,68498842,70992803,NaN,NaN,27.769042,-82.335967,23158,2,2,613,0,0,0,0,27.880,62.365784,20220121,190138,155040803,27.848664,-82.672092,27.880,-25.219,0.0,0.0,264.13315,-0.732427,16472.870918
7311099,1041020220120201926,10410,73166462,74600148,NaN,NaN,NaN,NaN,13618,2,2,811,0,0,0,0,24.489,54.780333,20220120,201926,159631448,27.951832,-82.364777,24.489,-27.927,0.0,0.0,-297.21417,-0.086139,16281.491147
9531756,1044320220125203751,10443,74271908,77037207,27.805708,-82.746451,27.793622,-82.335905,27472,0,0,338,0,183,0,0,30.145,67.432444,20220125,203751,74272507,27.913774,-82.496596,30.145,-18.118,0.0,0.0,-235.75578,0.458834,15897.588541
4336895,100502022011411312,10050,4392761,6398864,27.914649,-82.343909,28.047848,-82.743620,20021,0,0,44,0,0,0,0,27.974,62.576056,20220114,11312,4393761,27.950734,-82.374151,27.974,-25.566,0.0,0.0,244.35995,-0.455825,15291.081861

In [22]:
df.head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel,yawrate_speed
6990566,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,453922,40.092302,-83.050165,0.012333,221.0,NaN,NaN,NaN,NaN,NaN
6990567,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,454422,40.092302,-83.050165,0.009764,221.0,NaN,NaN,NaN,NaN,NaN
6990568,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,454930,40.092302,-83.050165,0.011306,221.0,NaN,NaN,NaN,NaN,NaN
6990569,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,455536,40.092302,-83.050165,0.020042,221.0,NaN,NaN,NaN,NaN,NaN
6990570,13520220120733,135,453422,512428,40.092302,-83.050165,40.092302,-83.050165,0,0,30,0,0,0,0,0,NaN,NaN,20220120,733,456122,40.092302,-83.050165,0.013361,221.0,NaN,NaN,NaN,NaN,NaN

In [23]:
df['speedDiff'] = df.groupby('tripId')['speedMph'].diff()
df['timediff'] = df.groupby('tripId')['localTimeMs'].diff()
df['timediff'] = df['timediff']/1000

In [24]:
df['speedDiff_ms'] = df['speedDiff']*0.44704

In [25]:
df['speedrate_ms2'] = df['speedDiff_ms']/(df['timediff'])

In [26]:
df['speedrate_ms2'].describe()

count    1.240889e+07
mean    -1.731961e-03
std      6.851347e-01
min     -3.350000e+02
25%     -1.388880e-01
50%      0.000000e+00
75%      1.540000e-01
max      8.459990e+02
Name: speedrate_ms2, dtype: float64

In [27]:
df.sort_values(by = 'speedrate_ms2',ascending = False).head()

,tripId,device,startlocaltime,endlocaltime,startlatitude,startlongitude,endlatitude,endlongitude,numBSMTx,numGNSSOutages,numCANOutages,numNormalBSMRx,numShadowBSMRx,numSPATRx,numWarnings,numInforms,speed,speedMph,filedate,filetimeutc,localTimeMs,latitude,longitude,gpsspeed,elevation,brakestatus,turnsignal,yawrate,longaccel,yawrate_speed,speedDiff,timediff,speedDiff_ms,speedrate_ms2
1905595,1042920220107170402,10429,61442010,67720263,NaN,NaN,27.837608,-82.287770,61293,4,4,526,0,358,0,0,9.883999,22.109876,20220107,170402,148067581,27.943284,-82.468558,9.884,-21.414,0.0,0.0,2.446706,0.876959,54.096366,1.892446,0.001,0.845999,845.998999
1905492,1042920220107170402,10429,61442010,67720263,NaN,NaN,27.837608,-82.287770,61293,4,4,526,0,358,0,0,13.513000,30.227720,20220107,170402,148014580,27.944604,-82.472381,13.513,-21.578,0.0,0.0,-0.814731,0.356453,24.627449,0.592786,0.001,0.264999,264.999000
9169776,1002820220124214943,10028,78583090,79299044,NaN,NaN,27.951274,-82.295141,6921,0,0,0,0,0,0,0,12.950000,28.968325,20220124,214943,165437057,27.951450,-82.302150,12.950,-13.377,0.0,0.0,0.812697,-0.078922,23.542456,0.107373,0.001,0.048000,48.000000
9169446,1002820220124214943,10028,78583090,79299044,NaN,NaN,27.951274,-82.295141,6921,0,0,0,0,0,0,0,20.156000,45.087688,20220124,214943,165270555,27.966148,-82.298155,20.156,-14.615,0.0,0.0,0.225164,0.067968,10.152126,0.058160,0.001,0.026000,26.000000
9169778,1002820220124214943,10028,78583090,79299044,NaN,NaN,27.951274,-82.295141,6921,0,0,0,0,0,0,0,12.958000,28.986220,20220124,214943,165437557,27.951392,-82.302150,12.958,-13.429,0.0,0.0,0.542080,0.175756,15.712853,0.055923,0.001,0.025000,25.000000

In [35]:
df.loc[df['timediff'] < 0.1, 'speedrate_ms2'] = np.nan

In [36]:
df['speedrate_ms2'].describe()

count    1.240888e+07
mean    -1.793204e-03
std      6.288663e-01
min     -3.216000e+01
25%     -1.388880e-01
50%      0.000000e+00
75%      1.540000e-01
max      1.900600e+01
Name: speedrate_ms2, dtype: float64

In [37]:
df[df['speedrate_ms2'] > 1.5].shape

(273768, 34)

In [38]:
df[df['speedrate_ms2'] < -1.5].shape

(348969, 34)

In [39]:
df['sudden_acceleration'] = df['speedrate_ms2'] > 1.5
df['sudden_decceleration'] = df['speedrate_ms2'] < -1.5

In [40]:
df['yawrate'].describe()

count    1.241479e+07
mean     1.327793e-02
std      5.861257e+00
min     -3.271133e+02
25%     -1.748792e-01
50%      0.000000e+00
75%      2.109049e-01
max      3.273949e+02
Name: yawrate, dtype: float64

In [41]:
df['accelerated_turn'] = (df['sudden_acceleration'] & (abs(df['yawrate']) > 30))

In [42]:
df['accelerated_turn'].value_counts()

False    12692316
True         6450
Name: accelerated_turn, dtype: int64

In [43]:
df['sudden_acceleration'].value_counts()

False    12424998
True       273768
Name: sudden_acceleration, dtype: int64

In [44]:
df['sudden_decceleration'].value_counts()

False    12349797
True       348969
Name: sudden_decceleration, dtype: int64